### ISSUE TITLE
Example source code isn't working!

### ISSUE THREAD

**Issue by wilz05** [balabanferhat/FlutterGetXWithNavigation#1]
Screenshot of the project looks amazing... I was looking for the same. have you tried your uploaded source code
 in a fresh newly created simulator I tried on a new android simulator it seems to be not working. 
could you please look into it

**Comment by balabanferhat** [comment]
Hi, yes I have tried. Can you share the error you are getting?

**Comment by wilz05** [comment]
On run, it goes to  SplashController  onInit

```

  if (loginController.myUser_val.value == "") {// this is true
      initialRoute = AppPages.LOGIN; //  sets the variable does nothing 
    } else {
      User loggedInUser =
          User.fromJson(jsonDecode(loginController.myUser_val.value));
      loginController.myUser.value = loggedInUser;
    }
// comes to the below
    Future.delayed(const Duration(seconds: 3), () {
      //Get.offAllNamed(initialRoute);

      mySnackbarWithRetry(
          "Veri erişiminde bir problem oluştu. Lütfen internet bağlantınızı kontrol edip tekrar deneyiniz!");
    });

```

![Screenshot_1636101542](https://user-images.githubusercontent.com/19764167/140482549-b5e1981f-bc3d-40ba-9f7c-135f93fdee5a.png)


```
[Getx]On init SplashController
[GETX] Instance "SplashController" has been created
[GETX] Instance "SplashController" has been initialized
[GETX] OPEN SNACKBAR
```

**Comment by balabanferhat** [comment]
Can you please check the last commit. There was a test snackbar code. Now it is commented...

**Comment by balabanferhat** [comment]
I think we can close this issue.
